### ISSUE TITLE
is there any way to test this feature locally

### ISSUE THREAD

**Issue by hsnandeeshgowda** [sandeshnaroju/react-native-in-app-update#1]
i followed the blog and completed the steps, **how can i test this feature**, or is there anything i am missing here.

versions :
    **react-native :- 0.61.5**
     **react :- 16.13.1**

**Comment by sandeshnaroju** [comment]
Have you tried internal app sharing feature in google play store? Scroll to the bottom in this link. and read internal app sharing section. https://developer.android.com/guide/playcore/in-app-updates
If you find difficulty in understanding, let me know, i will update the blog with testing

**Comment by hsnandeeshgowda** [comment]
i tried it, but when i am uploading the APK file to internal app sharing, i am getting this error "**You don't have permission to use internal app sharing for 'com.example.app'**".

app is not yet published to play store yet

**Comment by sandeshnaroju** [comment]
Please check this so thread https://stackoverflow.com/questions/57442473/you-don-t-have-permission-to-use-internal-app-sharing-for-your-app

**Comment by hsnandeeshgowda** [comment]
thank you so much for the blog, i tried it with existing play store apk, it worked,

**Comment by hsnandeeshgowda** [comment]
if you planning to make npm package for this let me know hsnandeeshgowda@gmail.com, interested in contributing, i am more into javascript, can contribute in javascript side

**Comment by Vanns35** [comment]
Should I need to upload on the play store to test the feature? Because react-native run-android --variant=release didn't work for me..

**Comment by hsnandeeshgowda** [comment]
Yes, you need to upload it in play console internal app sharing to test, I followed the below steps.
https://developer.android.com/guide/playcore/in-app-updates#internal-app-sharing -> steps to test

**Comment by divyasri93** [comment]
I've followed the steps and finally while debugging using the link from internal app sharing, its redirected to playstore with my app opened but Install button is missing in it! My app is supported only in US. I'm trying out from a different country. Could that be the reason? Kindly clarify, Thanks
