### ISSUE TITLE
error: package com.google.android.material.snackbar does not exist

### ISSUE THREAD

**Issue by Vanns35** [sandeshnaroju/react-native-in-app-update#2]
I followed your steps and implemented the In-App Module but I am getting an error in InAppUpdateModule.java.

**Comment by sandeshnaroju** [comment]
I forgot to include a depenedency. kindly add below line 

implementation 'com.google.android.material:material:1.0.0'

in gradle file. If you don't know how to add just refer to 1st point of how to use section.

**Comment by Vanns35** [comment]
error: cannot find symbol
          packages.add(new InAppUpdatePackage());

Now It is showing the above error ( and I've also manually changed com.example to com.MyProjectName in .java files )

**Comment by blitzve0** [comment]
Bro You need to add this to the readme section, i faced the same issue and found solution using this
