### ISSUE TITLE
It seems to be working, but new app version never reflects

### ISSUE THREAD

**Issue by shubhamkes** [sandeshnaroju/react-native-in-app-update#3]
Thank you for such a beautiful instruction for incorporating inApp update. I am able to install the package, but I never gets to see new version of app.

**Comment by sandeshnaroju** [comment]
where do you want/have to see the new version of app? may be check this #1

**Comment by shubhamkes** [comment]
I am using react-native-device-info to show the version. After successfully installation, when app reopens, it doesnt reflect new version which means app is not updated.

**Comment by sandeshnaroju** [comment]
Usually, you will get a popup or fullscreen if there is an update. After installing you may see the new version. follow the instructions here #1

**Comment by sandeshnaroju** [comment]
closing it as there is no reply
