### ISSUE TITLE
Snackbar issue

### ISSUE THREAD

**Issue by santhoshkumarvgds** [sandeshnaroju/react-native-in-app-update#4]
package com.google.android.material.snackbar does not exist
import com.google.android.material.snackbar.Snackbar;

im getting this issue?

**Comment by sandeshnaroju** [comment]
I forgot to include a depenedency. kindly add below line

implementation 'com.google.android.material:material:1.0.0'

in gradle file. If you don't know how to add just refer to 1st point of how to use section.


it is mentioned in issue #2
