### ISSUE TITLE
No update popup

### ISSUE THREAD

**Issue by shrutiraoniit25** [sandeshnaroju/react-native-in-app-update#6]
I followed everything but couldn't get any update or any update popup in app while I changed the version
here are the screenshots of the  code...
![Screenshot (117)](https://user-images.githubusercontent.com/42043257/124571316-4d9b0400-de65-11eb-8973-82d5776d6e9e.png)
![Screenshot (118)](https://user-images.githubusercontent.com/42043257/124571325-4f64c780-de65-11eb-82f3-04d7bb9e0f84.png)
![Screenshot (119)](https://user-images.githubusercontent.com/42043257/124571326-4ffd5e00-de65-11eb-8d22-df781f4b2281.png)

**Comment by sandeshnaroju** [comment]
How are you testing it? Are you following this https://developer.android.com/guide/playcore/in-app-updates/test ?

**Comment by shrutiraoniit25** [comment]
It is working now the only thing is like if put an updated version in play store
![Screenshot (120)](https://user-images.githubusercontent.com/42043257/124725425-7a651f00-df2a-11eb-8398-a5850d046700.png)
 yesterday then today it notified me for the update 
...How can I make it an immediate update

I have made my code like this for an immediate update...

**Comment by sandeshnaroju** [comment]
Long back, I wrote a blog on how to use it and understand it https://www.naroju.com/implementing-android-in-app-updates-in-react-native/ 

Also read about IMMEDIATE and FLEXIBLE differences here  https://developer.android.com/guide/playcore/in-app-updates

**Comment by sandeshnaroju** [comment]
Closing as there is no response
