### ISSUE TITLE
Nothing happens on clicking Restart after downloading the update

### ISSUE THREAD

**Issue by shivam0831** [sandeshnaroju/react-native-in-app-update#7]
After downloading the app update I got the Restart option in the snack bar but nothing happens after clicking on restart. Any solution?

**Comment by sandeshnaroju** [comment]
does not it restart? is it crashing?

**Comment by shivam0831** [comment]
after clicking on restart it stays on the same page

**Comment by shivam0831** [comment]
after making singed apk update dialog is not showing

**Comment by sandeshnaroju** [comment]
Apologies for late reply, I was busy with some other work. Normally, the In App Update should be tested in signed release (https://developer.android.com/guide/playcore/in-app-updates/test) build not in debug mode. If you don't see the update immediately, some times it takes few hours to show the update.

**Comment by sandeshnaroju** [comment]
closing as there is no response

**Comment by shivam0831** [comment]
I was checking in a signed release apk.

**Comment by sandeshnaroju** [comment]
If you have done everything right, then in your case  the native `UpdateAvailability.UPDATE_AVAILABLE` is not becoming true, i found it is happening sometimes, i found it is taking few hours. This lib is can't deal with that directly, we only use it. It is just a react native module for the native code.
