### ISSUE TITLE
error: cannot find symbol   packages.add(new InAppUpdatePackage());

### ISSUE THREAD

**Issue by akashi7** [sandeshnaroju/react-native-in-app-update#8]
followed your steps but i get error here

**Comment by sandeshnaroju** [comment]
Looks like you have not added given two files to your java code properly.

**Comment by jeesunikim** [comment]
Hey @akashi7, I ran into the same issue. I solved it by making sure [the package name](https://github.com/sandeshnaroju/react-native-in-app-update/blob/master/InAppUpdateModule.java#L1) is the same at the top of the files for `MainApplication.java`, `InAppUpdateModule.java`, and `InAppUpdatePackage.java`.
